# Generated by Django 4.2.23 on 2025-08-25 16:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job Category",
                "verbose_name_plural": "Job Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("soft", "Soft Skills"),
                            ("language", "Language"),
                            ("certification", "Certification"),
                            ("other", "Other"),
                        ],
                        default="technical",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Job Skill",
                "verbose_name_plural": "Job Skills",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Template description", null=True
                    ),
                ),
                ("title_template", models.CharField(max_length=200)),
                ("description_template", models.TextField()),
                ("responsibilities_template", models.TextField()),
                ("requirements_template", models.TextField()),
                ("nice_to_have_template", models.TextField(blank=True, null=True)),
                (
                    "default_job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "default_experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("junior", "Junior"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                            ("principal", "Principal"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.jobcategory",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Template",
                "verbose_name_plural": "Job Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("company_name", models.CharField(max_length=200)),
                ("description", models.TextField(help_text="Detailed job description")),
                (
                    "responsibilities",
                    models.TextField(help_text="Key responsibilities and duties"),
                ),
                (
                    "requirements",
                    models.TextField(help_text="Required qualifications and skills"),
                ),
                (
                    "nice_to_have",
                    models.TextField(
                        blank=True, help_text="Preferred qualifications", null=True
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("junior", "Junior"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                            ("principal", "Principal"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="City, Country or Remote", max_length=200
                    ),
                ),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (USD, EUR, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "salary_period",
                    models.CharField(
                        choices=[
                            ("hourly", "Per Hour"),
                            ("daily", "Per Day"),
                            ("weekly", "Per Week"),
                            ("monthly", "Per Month"),
                            ("yearly", "Per Year"),
                        ],
                        default="yearly",
                        max_length=20,
                    ),
                ),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "application_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "application_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("posted_to_linkedin", models.BooleanField(default=False)),
                (
                    "linkedin_post_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("linkedin_post_url", models.URLField(blank=True, null=True)),
                ("linkedin_posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "unipile_account_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "unipile_post_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("application_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.jobcategory",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="jobs", to="jobs.jobskill"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnipileWebhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "webhook_type",
                    models.CharField(
                        choices=[
                            ("account_status", "Account Status Update"),
                            ("messaging", "Messaging Events"),
                            ("mailing", "Mailing Events"),
                            ("mail_tracking", "Mail Tracking Events"),
                            ("users_relations", "Users Relations Events"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_id", models.CharField(max_length=200, unique=True)),
                ("account_id", models.CharField(blank=True, max_length=200, null=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.job",
                    ),
                ),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unipile Webhook",
                "verbose_name_plural": "Unipile Webhooks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["webhook_type", "processed"],
                        name="jobs_unipil_webhook_e71fa4_idx",
                    ),
                    models.Index(
                        fields=["account_id", "event_type"],
                        name="jobs_unipil_account_c88543_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("applicant_name", models.CharField(max_length=200)),
                ("applicant_email", models.EmailField(max_length=254)),
                (
                    "applicant_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("applicant_linkedin", models.URLField(blank=True, null=True)),
                ("applicant_portfolio", models.URLField(blank=True, null=True)),
                ("cover_letter", models.TextField(blank=True, null=True)),
                (
                    "resume_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "resume_text",
                    models.TextField(
                        blank=True, help_text="Extracted text from resume", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interviewed", "Interviewed"),
                            ("rejected", "Rejected"),
                            ("hired", "Hired"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "applied_via",
                    models.CharField(
                        choices=[
                            ("website", "Company Website"),
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=50,
                    ),
                ),
                ("recruiter_notes", models.TextField(blank=True, null=True)),
                ("interview_feedback", models.TextField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("status_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-applied_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "status"], name="jobs_jobapp_job_id_08192b_idx"
                    ),
                    models.Index(
                        fields=["status", "applied_at"],
                        name="jobs_jobapp_status_6642d6_idx",
                    ),
                ],
                "unique_together": {("job", "applicant_email")},
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "published_at"], name="jobs_job_status_d968cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["recruiter", "status"], name="jobs_job_recruit_b1d463_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["category", "status"], name="jobs_job_categor_2e2729_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_type", "experience_level"],
                name="jobs_job_job_typ_33354c_idx",
            ),
        ),
    ]
